# Generated by Django 5.2.4 on 2025-08-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_remove_individuallabor_user_remove_mukkadam_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='home_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
