# Generated by Django 5.2.4 on 2025-08-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_labourneed'),
    ]

    operations = [
        migrations.AddField(
            model_name='labourneed',
            name='status',
            field=models.CharField(default='latest', max_length=255),
        ),
    ]
