# Generated by Django 5.2.4 on 2025-08-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('waiting_for_response', 'Waiting for Response'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('awaiting_leader_confirmation', 'Awaiting Leader Confirmation'), ('open_for_bidding', 'Open for Bidding')], default='pending', max_length=40),
        ),
    ]
