# Generated by Django 5.2.4 on 2025-08-11 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0023_job_bidding_deadline_mukkadam_user_jobbid'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidReview',
            fields=[
            ],
            options={
                'verbose_name': 'Bid Review',
                'verbose_name_plural': 'Bid Reviews',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('registration.jobbid',),
        ),
    ]
