# Generated by Django 5.2.4 on 2025-08-11 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0024_bidreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobLeaderAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_allocations', to='registration.job')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_allocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('job', 'leader')},
            },
        ),
    ]
