# Generated by Django 5.1.6 on 2025-07-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_individuallabor_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individuallabor',
            name='adult_men_seeking_employment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='individuallabor',
            name='adult_women_seeking_employment',
            field=models.IntegerField(default=0),
        ),
    ]
