# Generated by Django 5.2.4 on 2025-08-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_transport_home_address_transport_whatsapp_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabourNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=20, unique=True)),
                ('farmer', models.UUIDField()),
                ('created_at', models.DateTimeField()),
                ('labour_count', models.PositiveIntegerField()),
                ('activities', models.JSONField()),
                ('date_needed', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('location', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
