# Generated by Django 5.2.4 on 2025-08-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_job_jobassignment_jobleaderresponse_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='leader_quoted_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The final price quoted by the leader.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='leader_response_message',
            field=models.TextField(blank=True, help_text='Notes or response from the team leader.', null=True),
        ),
    ]
