# Generated by Django 5.2.4 on 2025-08-09 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_alter_job_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workerstatus',
            name='proposed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_workers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workerstatus',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('proposed', 'Proposed for a Job'), ('not_available', 'Not Available')], default='available', max_length=15),
        ),
    ]
