# Generated by Django 5.2.4 on 2025-08-09 08:52

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('registration', '0016_workerstatus_proposed_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobassignment',
            old_name='laborer_content_type',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='jobassignment',
            old_name='laborer_object_id',
            new_name='object_id',
        ),
        migrations.AlterUniqueTogether(
            name='jobassignment',
            unique_together={('job', 'content_type', 'object_id')},
        ),
        migrations.CreateModel(
            name='JobStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assigned to Job'), ('mobilizing', 'Mobilizing'), ('transport_arranged', 'Transport Arranged'), ('en_route', 'En Route to Site'), ('on_site', 'Arrived at Site'), ('work_started', 'Work Started'), ('work_in_progress', 'Work in Progress'), ('work_completed', 'Work Completed'), ('payment_processed', 'Payment Processed')], max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='registration.jobassignment')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
