# Generated by Django 5.2.4 on 2025-08-09 10:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_jobstatusupdate_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobStatusUpdate',
            new_name='StatusUpdate',
        ),
    ]
