# Generated by Django 5.2.4 on 2025-08-11 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0021_labouradvancedprofiles_delete_labouradvancedprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LabourAdvancedProfiles',
            new_name='LaboursAdvancedProfiles',
        ),
    ]
