# Generated by Django 5.2.4 on 2025-08-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0025_jobleaderallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobbid',
            name='registered_labourers',
            field=models.ManyToManyField(blank=True, related_name='bids_included_in', to='registration.individuallabor'),
        ),
    ]
