# Generated by Django 5.2.4 on 2025-08-26 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0028_jobbid_status_jobfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('Transport', 'Transport Help'), ('Advance', 'Advance Money'), ('Accommodation', 'Accommodation'), ('Other', 'Other')], max_length=50)),
                ('details', models.TextField(blank=True, help_text="Details if request type is 'Other' or for additional info.")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_requests', to='registration.jobassignment')),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredLabourer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(blank=True, max_length=15)),
                ('mukkadam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_labourers', to='registration.mukkadam')),
            ],
            options={
                'unique_together': {('mukkadam', 'name')},
            },
        ),
    ]
