version: '3.8'

services:
  backend:
    build: ./backend
    command: /app/startup.sh
    restart: always
    expose:
      - "8000"
    volumes:
      # Volumes for sharing static and media files with Nginx
      - staticfiles_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      # --- IMPORTANT: Fill in your secrets here ---
      - SECRET_KEY=fruwiuuiiuhUUIHFE(*&^&%^**(*&%$$^&&*^$$##$))
      - DEBUG=0
      - ALLOWED_HOSTS=65.2.178.170,kishan.kisanmitra.ai,backend #<-- Your server IP
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=bhatikarn634@gmail.com
      - DJANGO_SUPERUSER_PASSWORD=z0k5NgbdYn5f8szqKSXx


      # --- Credentials for your SINGLE AWS RDS Database ---
      - POSTGRES_DB=supplysidelabourdbnew
      - POSTGRES_USER=supplysidelabour
      - POSTGRES_PASSWORD=z0k5NgbdYn5f8szqKSXx
      - POSTGRES_HOST=supplysidelabour.c12ggig2u4ig.ap-south-1.rds.amazonaws.com
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    restart: always
    volumes:
      # ADDED THESE TWO LINES for static and media files
      - staticfiles_volume:/app/staticfiles:ro
      - media_volume:/app/media:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
volumes:
  staticfiles_volume:
  media_volume: