FROM ghcr.io/osgeo/gdal:ubuntu-full-3.8.3

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Install Python + pip (gdal already present in base image)
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy requirements first (better for caching)
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir gunicorn && \
    pip install --no-cache-dir -r requirements.txt

# Copy rest of the project
COPY . .

# Make startup script executable
RUN chmod +x startup.sh

CMD ["./startup.sh"]


