  GNU nano 7.2                 backend/dockerfile                           # Use a pre-built image that includes GDAL
FROM ghcr.io/osgeo/gdal:ubuntu-full-3.8.3

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# No need to install gdal-bin or libgdal-dev as they are in the base image
# RUN apt-get update && apt-get install -y \
#     gdal-bin \
#     libgdal-dev \
#     build-essential \
#     && rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir gunicorn -r requirements.txt

COPY . .

RUN chmod +x /app/startup.sh

# The CMD or ENTRYPOINT command to run your app will go here, or in your do>