# Generated by Django 5.1.6 on 2025-07-22 10:51

import django.contrib.gis.db.models.fields
import registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individuallabor',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='GPS coordinates (longitude, latitude)', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='individuallabor',
            name='location_accuracy',
            field=models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True),
        ),
        migrations.AddField(
            model_name='individuallabor',
            name='location_timestamp',
            field=models.DateTimeField(blank=True, help_text='When location was captured', null=True),
        ),
        migrations.AddField(
            model_name='mukkadam',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='GPS coordinates (longitude, latitude)', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='mukkadam',
            name='location_accuracy',
            field=models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True),
        ),
        migrations.AddField(
            model_name='mukkadam',
            name='location_timestamp',
            field=models.DateTimeField(blank=True, help_text='When location was captured', null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='GPS coordinates (longitude, latitude)', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='others',
            name='location_accuracy',
            field=models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='location_timestamp',
            field=models.DateTimeField(blank=True, help_text='When location was captured', null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='GPS coordinates (longitude, latitude)', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='transport',
            name='location_accuracy',
            field=models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='location_timestamp',
            field=models.DateTimeField(blank=True, help_text='When location was captured', null=True),
        ),
        migrations.AlterField(
            model_name='individuallabor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=registration.models.photo_upload_path),
        ),
        migrations.AlterField(
            model_name='mukkadam',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=registration.models.photo_upload_path),
        ),
        migrations.AlterField(
            model_name='others',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=registration.models.photo_upload_path),
        ),
        migrations.AlterField(
            model_name='transport',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=registration.models.photo_upload_path),
        ),
    ]
