# Generated by Django 5.1.6 on 2025-07-24 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_individuallabor_adult_men_seeking_employment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individuallabor',
            name='home_address',
        ),
        migrations.RemoveField(
            model_name='individuallabor',
            name='whatsapp_number',
        ),
        migrations.RemoveField(
            model_name='mukkadam',
            name='home_address',
        ),
        migrations.RemoveField(
            model_name='mukkadam',
            name='whatsapp_number',
        ),
        migrations.RemoveField(
            model_name='others',
            name='home_address',
        ),
        migrations.RemoveField(
            model_name='others',
            name='whatsapp_number',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='home_address',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='whatsapp_number',
        ),
    ]
