# Generated by Django 5.2.4 on 2025-08-04 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_individuallabor_user_mukkadam_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individuallabor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mukkadam',
            name='user',
        ),
        migrations.AlterField(
            model_name='individuallabor',
            name='mobile_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='individuallabor',
            name='referral_contact',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AlterField(
            model_name='mukkadam',
            name='mobile_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='others',
            name='mobile_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='transport',
            name='mobile_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
