# Generated by Django 5.2.4 on 2025-08-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('waiting_for_response', 'Waiting for Response'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('leader_confirmation', 'leader_Confirmation'), ('open_for_bidding', 'Open for Bidding')], default='pending', max_length=20),
        ),
    ]
