# Generated by Django 5.2.4 on 2025-08-11 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_rename_jobstatusupdate_statusupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabourAdvancedProfile',
            fields=[
                ('labour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='advanced_profile', serialize=False, to='registration.individuallabor')),
                ('available_dates', models.JSONField(blank=True, default=list, help_text='A list of dates in YYYY-MM-DD format.')),
                ('advanced_rate_per_day', models.DecimalField(decimal_places=2, help_text='The per-day rate this labourer has agreed to for advanced bookings.', max_digits=10)),
                ('requires_transport', models.BooleanField(default=True, help_text='Does this labourer require transport to be arranged and paid for?')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
