# Generated by Django 5.2.4 on 2025-08-11 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0022_rename_labouradvancedprofiles_laboursadvancedprofiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='bidding_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mukkadam',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mukadam_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='JobBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('workers_provided', models.PositiveIntegerField(default=0)),
                ('notes_on_skills', models.TextField(blank=True, help_text='Details on the skills of the workers provided.')),
                ('includes_transport', models.BooleanField(default=False)),
                ('includes_accommodation', models.BooleanField(default=False)),
                ('no_advance_required', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='registration.job')),
                ('mukadam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids_made', to='registration.mukkadam')),
            ],
            options={
                'ordering': ['bid_price'],
                'unique_together': {('job', 'mukadam')},
            },
        ),
    ]
